// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2yZ51lpZFtqQDpD8OrzOnhTyrv0cymE',
    appId: '1:193360515095:web:a857fc20b09e10c123cc52',
    messagingSenderId: '193360515095',
    projectId: 'project-chashmart',
    authDomain: 'project-chashmart.firebaseapp.com',
    storageBucket: 'project-chashmart.appspot.com',
    measurementId: 'G-QE87G6ES7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4qekeuElmY5a9wdOQ1W7sGHcgdoA-5Q',
    appId: '1:193360515095:android:50d023e84a5b419623cc52',
    messagingSenderId: '193360515095',
    projectId: 'project-chashmart',
    storageBucket: 'project-chashmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZDQ0vRqN1mHfzmCiFPPId8t8u7JHIlgc',
    appId: '1:193360515095:ios:a1f855eab9ab9dd323cc52',
    messagingSenderId: '193360515095',
    projectId: 'project-chashmart',
    storageBucket: 'project-chashmart.appspot.com',
    iosBundleId: 'com.example.projectchashmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZDQ0vRqN1mHfzmCiFPPId8t8u7JHIlgc',
    appId: '1:193360515095:ios:4eb9a289817a695c23cc52',
    messagingSenderId: '193360515095',
    projectId: 'project-chashmart',
    storageBucket: 'project-chashmart.appspot.com',
    iosBundleId: 'com.example.projectchashmart.RunnerTests',
  );
}
